#pragma config(Sensor, S2,     snrRHS,         sensorSONAR)
#pragma config(Sensor, S3,     lghtSNS,        sensorLightActive)
#pragma config(Sensor, S4,     snrFRNT,        sensorSONAR)
#pragma config(Motor,  motorB,          mtrRHS,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mtrLHS,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//CODE FOR ENGG282 - Concept 2
int maze[8][4]
void identify(){}
void shortestPath(){}
task main()
{
int results[0,1,2,3]

//1 is a junction, 2 is a corner, 3 is a deadend, 0 being straight
//Can start in any square, have to discern your own position from there, maybe hardcode it?

//maze is 8 units by 4 units - only 32 different squares to map
	while (true)
	{
		// The robot should only move not forward because of 1 of 3 reasons
		// 1. It senses a wall in front, so will turn right so as to not run into it
		// 2. It does not sense a wall on the right, so turns right to find a wall
		// 3. It sees the light and moves towards it

		tSonarFront();
		tSonarRight();
	}

}
// Concept 1: This
// Concept 2: Use Mapping algorithm
// Concept 2: Use curved edges to auto correct the robot
// Concept 3: bumper instead of sonar
